name: my_container_CI

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/**'
    branches: [ main, Environment/Github ]
  pull_request:
    paths:
      - 'src/**'
    branches: [ main ]

jobs:
  debian-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install library
        run: sudo apt-get install libcap-dev && sudo apt-get install libseccomp-dev

      - name: Install gtest manually
        run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib

      - name: symbolic link
        run: sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a

      - name: configure
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..

      - name: make
        run: cd build && make